#'''Parameter and computational resource config.'''#


ext: '/home/lam4003/bin/camp_mag-gold-std/workflow/ext'


# --- map_asm_ref --- #

map_asm_ref_threads: 20
map_asm_ref_mem_mb: 100000


# --- amber --- #

amber_mem_mb: 50000

